name: RaceDay Part 1 CI

on :
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  validate-project:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check required project files
        run:  | 
          test -f docs/RaceDayERD.drawio (1).png
          test -f docs/RceDay_Database.sql
          test -f docs/API_Endpoint_Plan.md
          test -f README.md
      
      - name: Validate repository structure
        run: |
          test -d docs
          test -d .github/workflows
      
      - name: Validation successful
        run: echo "RaceDay Part 1 repository structure is valid."
        